blog/urls.py
from django.urls import path
from blog        import views

app_name = 'blog'
urlpatterns = [
    path('', views.ArticlesView.as_view(), name='index'),
    path('articles/<int:pk>', views.view_article_details, name='single_article'),
]

event_keeper/urls.py
from django.urls import path

urlpatterns = [

]

events/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
    path('events/', include('event_keeper.urls')),

    path('', RedirectView.as_view(url='blog/')),
]

blog/models.py
from django.db import models

class Article(models.Model):
    name         = models.CharField(max_length=255)
    original_url = models.URLField()
    content      = models.TextField()
    post_date    = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-post_date',)

    def __str__(self):
        return self.name

class Comment(models.Model):
    article  = models.ForeignKey(Article, on_delete=models.CASCADE)
    username = models.CharField(max_length=255)
    body     = models.TextField()
    post_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-post_date',)

    def __str__(self):
        return f"{self.username} on {self.post_date}"

event_keeper/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.views     import generic
from blog.models      import Article, Comment

class ArticlesView(generic.ListView):
    model = Article

    paginate_by = 10

def view_article_details(request, pk):
    try:
        article = Article.objects.get(pk=pk)
    except Question.DoesNotExist:
        raise Http404("Article does not exist")

    if request.method == 'POST':
        comment = Comment(
            article=article,
            username=request.user.username,
            body=request.POST['comment_body']
        )

        comment.save()

    return render(request, 'blog/article.html', context={"article": article})

event_keeper/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/article.html
<h1>{{ article.name }}</h1>
<p>{{ article.summary }}</p>

<p><a href="{{ article.original_url }}">Link to the original<a></p>

<p>Posted at: {{ article.post_date }}<p>

<p>{{ article.content |safe }}</p>

<h3>Comments:</h3>

<ul>
{% for comment in article.comment_set.all %}
  <p>{{ comment.username }} at {{ comment.post_date }} said:</p>
  <p>{{ comment.body }}</p>
{% endfor %}
</ul>

{% if user.is_authenticated %}
<form method="post" action="{% url 'blog:single_article' article.id %}">
    {% csrf_token %}
    <input type="text" name="comment_body" />
    <input type="submit" value="comment" />
</form>
{% else %}
  <li><a href="{% url 'login'%}?next={{request.path}}">Login to make comments</a></li>
{% endif %}

blog/templates/blog/article_list.html
<h1>Articles</h1>

{% if article_list %}

<ul>
  {% for article in article_list %}
    <li>
      <a href="{% url 'blog:single_article' article.id %}"><h3>{{ article.name }}</h3></a>
    </li>
  {% endfor %}
</ul>

{% if is_paginated %}
  {% if page_obj.has_previous %}
    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
  {% endif %}

    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.

  {% if page_obj.has_next %}
    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
  {% endif %}
{% endif %}

{% else %}

<p>No articles available</p>

{% endif %}

<ul>